### ISSUE TITLE
Add new Textarea component

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui#10]
Create a new <Textarea /> component for the library:

![image](https://user-images.githubusercontent.com/65427911/138598877-3424f71c-b8d5-4979-aa75-a5fbb8011a4b.png)

Don't forget to use storybook to test your solution locally.

**Comment by inovux** [comment]
@jpalacio0612 Can I pick this up?

**Comment by jpalacio0612** [comment]
@inovux Sure, go ahead!

**Comment by inovux** [comment]
thanks! @jpalacio0612 Does it come in different sizes as well? Just like the `TextInput`? Or just 1 single size?

**Comment by jpalacio0612** [comment]
@inovux I think it should accept the same props as the TextInput: size, variant, onChange, placeholder. Thanks!

**Comment by inovux** [comment]
@jpalacio0612 thanks! Something like this ? https://github.com/jpalacio0612/react-neon-ui/pull/11
