### ISSUE TITLE
Add a new Divider component

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui#5]
Create a new component for the library. It is a simple divider:

![image](https://user-images.githubusercontent.com/65427911/137059388-999d1a2f-bf11-4660-8d2b-f53b4b2d0609.png)

As you can see in the image, the divider will have two forms, on and off, in addition to making sure that by default it occupies all the possible width. You can take the chakra-ui divider as an example: [https://chakra-ui.com/docs/data-display/divider](https://chakra-ui.com/docs/data-display/divider)

**Comment by Hina-softwareEngineer** [comment]
Hello, I want to work on this component. Can you assign it to me?

**Comment by jpalacio0612** [comment]
@Hina-softwareEngineer Sure, go ahead!

**Comment by jpalacio0612** [comment]
Closed by PR (#7)
